<?php
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
echo "sé loko mó preguiça :(";
?>